---
# handlers file for ansible-initial-server

# Alpine
# Ensure that local auto-start service is enabled
# - used to start ssh-host-keygen.sh on first boot and the auto-growpart script
- name: Activate Autostart
  service:
    name: local
    runlevel: default
    enabled: yes
  become: true

# Alpine, OpenBSD
- name: Restart SSHD
  service:
    name: sshd
    state: restarted
  become: true
  tags:
    - vanilla

# Debian, Ubuntu
- name: Restart SSH
  service:
    name: ssh
    state: restarted
  become: true
  tags:
    - vanilla

# Debian, Ubuntu
- name: Apply Network Configuration
  service:
    name: systemd-logind
    state: restarted
  become: true
  tags:
    - vanilla
    - travis

# OpenBSD
- name: Apply Network Settings
  command: sh /etc/netstart
  become: true
  tags:
    - vanilla
